FROM python:3.10-bullseye

COPY ./requirements-test.txt requirements-test.txt

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements-test.txt && pip cache purge

# docker build --progress plain -f Dockerfile-test -t mlserver-dev:0.0.1 .
