name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull --platform linux/amd64 gcr.io/kaniko-project/executor:v1.3.0
          docker tag  gcr.io/kaniko-project/executor:v1.3.0 ghcr.io/lanzhiwang/executor-amd64:v1.3.0
          docker push ghcr.io/lanzhiwang/executor-amd64:v1.3.0
