name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull --platform linux/amd64 registry.k8s.io/nfd/node-feature-discovery:v0.12.1

          docker tag registry.k8s.io/nfd/node-feature-discovery:v0.12.1 ghcr.io/lanzhiwang/registry.k8s.io/nfd/node-feature-discovery:v0.12.1

          docker push ghcr.io/lanzhiwang/registry.k8s.io/nfd/node-feature-discovery:v0.12.1

