name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull --platform linux/amd64 gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0

          docker tag gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0 ghcr.io/lanzhiwang/gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0

          docker push ghcr.io/lanzhiwang/gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
