name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull --platform linux/amd64 k8s.gcr.io/nfd/node-feature-discovery:v0.11.0

          docker tag k8s.gcr.io/nfd/node-feature-discovery:v0.11.0 ghcr.io/lanzhiwang/k8s.gcr.io/nfd/node-feature-discovery:v0.11.0

          docker push ghcr.io/lanzhiwang/k8s.gcr.io/nfd/node-feature-discovery:v0.11.0

