name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull --platform linux/amd64 ghcr.io/dexidp/dex:v2.31.2
          docker tag  ghcr.io/dexidp/dex:v2.31.2 ghcr.io/lanzhiwang/ghcr.io/dexidp/dex:v2.31.2
          docker push ghcr.io/lanzhiwang/ghcr.io/dexidp/dex:v2.31.2

