name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker pull and push
        run: |
          docker pull --platform linux/amd64 docker.io/istio/proxyv2:1.19.3

          docker tag docker.io/istio/proxyv2:1.19.3 docker.io/lanzhiwang/istio/proxyv2:1.19.3

          docker push docker.io/lanzhiwang/istio/proxyv2:1.19.3
